### ISSUE TITLE
Is there any roadmap for chaosctl

### ISSUE THREAD

**Issue by Yiyiyimu** [yeya24/chaosctl#2]
Hi @yeya24, I'm working on https://github.com/chaos-mesh/chaos-mesh/pull/1074 to easily print out debug information with ctl. 

Since I'm working on ctl, I think I could also add some other components to `chaosctl` besides `debug`. I noticed the draft PR in this repo is about to create chaos in ctl. Although for me it seems no better than the yaml way, do you have some other ideas on what the ctl could do for chaos-mesh~

**Comment by yeya24** [comment]
There is no roadmap for this project and it is deprecated now.

The idea of this tool is to interact with chaos-daemon directly via `gRPC`.
No other usage I can think about right now. If u want to add more features to the ctl, u can think about adding more gRPC APIs first.

**Comment by Yiyiyimu** [comment]
Sure thanks for the suggestions! 🍻
